spring.application.name=StudyMateAiBackend
server.port=8080

ai.service.base-url=http://127.0.0.1:8000
app.google.web-client-id=117487363987-auo2v0brhot4nmlm562qqcsmbatdngp5.apps.googleusercontent.com
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
app.jwt.secret=ThisIsASecretKeyForJwtThatMustBeAtLeast32CharactersLong
app.jwt.expiration-ms=86400000

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/StudyMateAi
spring.datasource.username=postgres
spring.datasource.password=2580
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Fix PostgreSQL LOB handling - prevents "Unable to access lob stream"
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Disable open-in-view to prevent lazy loading outside transactions
spring.jpa.open-in-view=false