// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe2lFXWqRSjtPm_Zd19F7PPofFmzicLBU',
    appId: '1:713095573719:web:ffee5944b255689c570092',
    messagingSenderId: '713095573719',
    projectId: 'studymateai-1a53b',
    authDomain: 'studymateai-1a53b.firebaseapp.com',
    storageBucket: 'studymateai-1a53b.firebasestorage.app',
    measurementId: 'G-YER2MQEJBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv01yQy4UQnL_0UdyjO0JLunRt_tNjMJU',
    appId: '1:713095573719:android:5870710bfd5ee58b570092',
    messagingSenderId: '713095573719',
    projectId: 'studymateai-1a53b',
    storageBucket: 'studymateai-1a53b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdX8n87vjixG6S4Xr6qxNJUKsSSjLTXy8',
    appId: '1:713095573719:ios:74c0f67221bf4145570092',
    messagingSenderId: '713095573719',
    projectId: 'studymateai-1a53b',
    storageBucket: 'studymateai-1a53b.firebasestorage.app',
    iosBundleId: 'com.example.studyMateAiFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdX8n87vjixG6S4Xr6qxNJUKsSSjLTXy8',
    appId: '1:713095573719:ios:74c0f67221bf4145570092',
    messagingSenderId: '713095573719',
    projectId: 'studymateai-1a53b',
    storageBucket: 'studymateai-1a53b.firebasestorage.app',
    iosBundleId: 'com.example.studyMateAiFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe2lFXWqRSjtPm_Zd19F7PPofFmzicLBU',
    appId: '1:713095573719:web:8c5e654955c36e51570092',
    messagingSenderId: '713095573719',
    projectId: 'studymateai-1a53b',
    authDomain: 'studymateai-1a53b.firebaseapp.com',
    storageBucket: 'studymateai-1a53b.firebasestorage.app',
    measurementId: 'G-GK70DSBRXX',
  );
}
